### ISSUE TITLE
En este repositorio hay ficheros y carpetas que no deberían estar

### ISSUE THREAD

**Issue by sambrista** [mfortea/HackBlog#1]
Si te fijas en el contenido de .gitignore, hay una serie de ficheros y carpetas que deberían ignorarse y, por tanto, no subirse al repositorio, entre ellas la carpeta vendor y la carpeta var. Sin embargo en tu repositorio está subida entera.

Te recomiendo que ejecutes el siguiente comando para quitar la carpeta del repositorio (pero no borrar tu copia local):
```bash
git rm --cached -r vendor/*
git rm --cached -r var/*
```
Por otro lado, deberías añadir el directorio .vscode a .gitignore y hacer lo mismo. De lo contrario, si trabajas con alguien más que use VS Code, cada vez que cambies una configuración se sube el cambio y se le cambia al resto del equipo.

No es necesario que subas archivos con capturas, yo clono el código, hago ``composer install`` para instalar las dependencias (rellenar la carpeta vendor) y lanzo el servidor para probarlo.

**Comment by mfortea** [comment]
Ya he actualizado el .gitignore para que tenga en cuenta el directorio .vscode/.
Las carpetas vendor y var han sido eliminadas.

**Comment by sambrista** [comment]
Perfecto. Issue cerrada.
